use_frameworks!

platform :ios, '8.0'

target 'ZHKCategories_Example' do
  
  pod 'ZHKCategories', :path => '../'
  pod 'ZHKCategories/UIKit', :path => '../'

  target 'ZHKCategories_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
